name: frontend
description: "A new Flutter project."
publish_to: 'none'  # Prevent accidental publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^0.13.6
  flutter_secure_storage: ^9.0.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  file_picker: ^10.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

 
